# Enable all rules by default
include: all_lint_rules.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Otherwise cause the import of all_lint_rules to warn because of some rules conflicts.
    # The conflicts are fixed in this file instead, so we can safely ignore the warning.
    included_file_warning: ignore
# Explicitly disable only the rules we do not want.
linter:
  rules:
    # Some explanation why we don't want this lint
    always_put_required_named_parameters_first: false
    prefer_double_quotes: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_types_on_closure_parameters: false
    unnecessary_final: false
    prefer_relative_imports: false
    omit_local_variable_types: false
    diagnostic_describe_all_properties: false
